import tkinter
from tkinter import *
top=tkinter.Tk()
top.title("Notepad")
txt=Text(top,width="1200",height="800")
txt.pack()
m=Menu(top)
file=Menu(m,tearoff=False)
file.add_command(label="New                                          Ctrl+N")
file.add_command(label="New Window                Ctrl+Shift+N")
file.add_command(label="Open...                                      Ctrl+O")
file.add_command(label="Save                                           Ctrl+S")
file.add_command(label="Save As...                        Ctrl+Shift+S")
file.add_separator()
file.add_command(label="Page Setup...")
file.add_command(label="Print...                                        Ctrl+P")
file.add_separator()
file.add_command(label="Exit",command=quit)
m.add_cascade(label="File",menu=file)
edit=Menu(m,tearoff=False)
edit.add_command(label="Undo")
edit.add_separator()
edit.add_command(label="cut")
edit.add_command(label="copy")
edit.add_command(label="Paste")
edit.add_command(label="Delete")
edit.add_separator()
edit.add_command(label="Search With Being...")
edit.add_command(label="Find...")
edit.add_command(label="Find Next")
edit.add_command(label="Find Previous")
edit.add_command(label="Replace...")
edit.add_command(label="Go To...")
edit.add_separator()
edit.add_command(label="Select All")
edit.add_command(label="Time/Date")
m.add_cascade(label="Edit",menu=edit)
formate=Menu(m,tearoff=False)
formate.add_command(label="Word Wrap")
formate.add_command(label="Font...")
m.add_cascade(label="Formate",menu=formate)
view=Menu(m,tearoff=False)
zoom = Menu(view, tearoff=False)
zoom.add_command(label="Zoom In                                   Ctrl+Plus")
zoom.add_command(label="Zoom Out                                Ctrl+Minus")
zoom.add_command(label="Restore Default Zoom            Ctrl+O")
view.add_cascade(label="Zoom",menu=zoom)
view.add_command(label="Status Bar")
m.add_cascade(label="View",menu=view)
hp=Menu(m,tearoff=False)
hp.add_command(label="View Help")
hp.add_command(label="Send Feeback")
hp.add_separator()
hp.add_command(label="About Notepad")
m.add_cascade(label="Help",menu=hp)
top.config(menu=m)
top.mainloop()